# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'

            
          cat '$(Build.SourcesDirectory)/KubeYaml/yaml/benefits.yaml'

          echo 'Hello world 0'  
          value=`cat '$(Build.SourcesDirectory)/KubeYaml/yaml/benefits.yaml'`


          echo 'Hello world 0.25'  
          value=${value//##BUILD_ID##/$(Build.BuildId)}
          

          echo "$value" > '$(Build.SourcesDirectory)/KubeYaml/yaml/benefits_build.yaml'

          echo 'Hello world 1'  
          value1=`cat '$(Build.SourcesDirectory)/KubeYaml/yaml/benefits_build.yaml'`
          echo 'Hello world 2'  
          echo "$value1"
           
          