# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: DownloadPipelineArtifact@2
      displayName: Download artifactory
      inputs:
        buildType: 'specific'
        project: '791b40cb-dc87-4739-80ec-ff42b488ab64'
        definition: '13'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        targetPath: '$(Pipeline.Workspace)/download'
    