# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3fb5e577-f47e-4ad8-ae58-ab6cebb62002'
  imageRepositorybenefits: 'benefits'
  imageRepositoryhealthcare: 'healthcare'
  containerRegistry: 'dockerstore.azurecr.io'
  dockerbenefitsfilePath: '$(Build.SourcesDirectory)/Leon/Benefits/Dockerfile'
  dockerhealthcarefilePath: '$(Build.SourcesDirectory)/Leon/Healthcare/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAllMicroservices
  displayName: Build and push stage
  jobs:  
  - job: BuildBenefits
    displayName: Build Benefits Microservice
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepositorybenefits)
        dockerfile: $(dockerbenefitsfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: BuildHealthcare
    displayName: Build Healthcare Microservice
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryhealthcare)
        dockerfile: $(dockerhealthcarefilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
